#!/usr/bin/env python3
"""Convert a PNG sprite to a Lua data module for pokedex.nvim.

Usage:
  png_to_lua.py <input.png> <output.lua>

Output format:
  return {
    width = N,
    height = N,
    palette = { "rrggbb", ... },
    pixels = {
      "...",  -- width chars per row, height rows
    },
  }

Where each pixel char is:
  "."          transparent
  "1"-"9"      palette index 1-9
  "a"-"z"      palette index 10-35
"""
from __future__ import annotations

import sys
from pathlib import Path
from PIL import Image

ALPHA_THRESHOLD = 128
TRANSPARENT = "."


def encode_idx(idx: int) -> str:
    if idx == 0:
        return TRANSPARENT
    if 1 <= idx <= 9:
        return str(idx)
    if 10 <= idx <= 35:
        return chr(ord("a") + idx - 10)
    raise ValueError(f"palette index {idx} exceeds 35 (a-z); add more chars if needed")


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(f"usage: {argv[0]} <input.png> <output.lua>", file=sys.stderr)
        return 1
    src = Path(argv[1])
    dst = Path(argv[2])

    img = Image.open(src).convert("RGBA")
    w, h = img.size
    px = img.load()

    palette: list[tuple[int, int, int]] = []
    palette_idx: dict[tuple[int, int, int], int] = {}
    rows: list[str] = []
    for y in range(h):
        chars = []
        for x in range(w):
            r, g, b, a = px[x, y]
            if a < ALPHA_THRESHOLD:
                chars.append(TRANSPARENT)
            else:
                key = (r, g, b)
                if key not in palette_idx:
                    palette.append(key)
                    palette_idx[key] = len(palette)
                chars.append(encode_idx(palette_idx[key]))
        rows.append("".join(chars))

    palette_str = ", ".join(f'"{r:02x}{g:02x}{b:02x}"' for r, g, b in palette)
    lines = [
        "-- Auto-generated by scripts/png_to_lua.py. Do not edit by hand.",
        "return {",
        f"  width = {w},",
        f"  height = {h},",
        f"  palette = {{ {palette_str} }},",
        "  pixels = {",
    ]
    for row in rows:
        lines.append(f'    "{row}",')
    lines.append("  },")
    lines.append("}")
    dst.write_text("\n".join(lines) + "\n")
    print(f"wrote {dst}: {w}x{h}, {len(palette)} colors", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
